adds `start_command` to service resource
terraform-community-providers/terraform-provider-railway pull request #15
Opened 2023-08-15 14:05 UTC by matifali

2023-08-15 20:17 UTC, pksunkara commented
`startCommand` is available in railway config file. https://docs.railway.app/deploy/config-as-code

As mentioned in the documentation:

> ⚠️ NOTE: All the other settings not specified here are recommended to be specified in the Railway config file.

Therefore, I am rejecting this PR.

2023-08-15 22:12 UTC, matifali commented
@pksunkara I am trying to make it closer or other terraform providers that directly support a start command. For example fly.io. It will make it easier to just specify an image source and start command without needing to create a railway config file and track it in a repo. 

```hcl
resource railway_service "workspace" {
  image_source = "codercom/enterprise-base"
  start_command = coder_agent.me.init_script
}
```
The issue with a railway config is that it is not straight forward to use a dynamic startup script as the start command. 

I am doing this in context of creating a native https://github.com/coder/coder template to be used with https://railway.app/template/coder. 

Thanks.

2023-08-15 23:10 UTC, pksunkara requested changes

2023-08-15 23:11 UTC, pksunkara commented
> I did not add the tests. I would be happy if you could guide me in completing it.

https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests is a good read.

2023-08-16 07:27 UTC, matifali commented on internal/provider/resource_service.go
> +			"start_command": schema.StringAttribute{
Sure, I will do that.

2023-08-24 14:57 UTC, pksunkara commented
Closing this until further update.

2023-08-24 14:57 UTC, closed without merging

2023-08-24 15:00 UTC, matifali commented
I don't think I will be able to find time to finish this any time in the near future. Thank you!